<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Risk Scores Report</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        h1 { text-align: center; color: #6d28d9; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: center; }
        th { background-color: #f8fafc; font-weight: bold; color: #1e293b; }
        .footer { position: fixed; bottom: -20px; left: 0; right: 0; text-align: center; font-size: 10px; color: #999; }
    </style>
</head>
<body>
    <h1>Historical Risk Scores Report</h1>
    
    <table>
        <thead>
            <tr>
                <th>Country</th>
                <th>Weather Risk</th>
                <th>Inflation Risk</th>
                <th>Currency Risk</th>
                <th>News Sentiment Risk</th>
                <th>Final Score</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($riskScores as $score)
            <tr>
                <td>{{ $score->country->name ?? 'N/A' }}</td>
                <td>{{ $score->weather_score }}</td>
                <td>{{ $score->inflation_score }}</td>
                <td>{{ $score->exchange_rate_score }}</td>
                <td>{{ $score->news_sentiment_score }}</td>
                <td><strong>{{ $score->final_risk_score }}</strong></td>
                <td>{{ $score->calculated_at }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by LogisticsCtrl - {{ date('Y-m-d H:i:s') }}
    </div>
</body>
</html>
